runtime: python37

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301


#- url: /v1/ui/.*
#  script: openapi_server.auth.redirect_credentials
#  secure: always
